---
- name: Install MySql
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - python-mysqldb
    - mysql-server

- name: Start the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql.root_password }}"
    login_user: root
    login_password: "{{ mysql.root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 

- name: Configure password less login for root
  sudo: yes
  template: src=root.my.cnf.tpl dest=/root/.my.cnf mode=0640
