---
- name: Check if Imagick is installed
  stat: "path=/usr/lib/php/20151012/imagick.so"
  register: imagick_bin

- name: Download Imagick build
  get_url:
    url: http://pecl.php.net/get/imagick-3.4.0RC6.tgz
    dest: /tmp/imagick-3.4.0RC6.tgz
    mode: 0755
  when: not imagick_bin.stat.exists

- name: Unpack Imagick
  command: tar xvzf imagick-3.4.0RC6.tgz
  args:
    chdir: /tmp
  when: not imagick_bin.stat.exists

- name: Phpize Imagick
  command: phpize
  args:
    chdir: /tmp/imagick-3.4.0RC6
  when: not imagick_bin.stat.exists

- name: Configure Imagick
  command: ./configure
  args:
    chdir: /tmp/imagick-3.4.0RC6
  when: not imagick_bin.stat.exists

- name: Configure Imagick
  command: make install
  args:
    chdir: /tmp/imagick-3.4.0RC6
  when: not imagick_bin.stat.exists

- name: Add imagick to php config
  copy: src=imagick/imagick.ini dest=/etc/php5/mods-available/
  when: not imagick_bin.stat.exists

- name: Enable imagick
  command: php5enmod imagick
  when: not imagick_bin.stat.exists

- name: Remove tmp files from Imagick build
  file: path={{item}} state=absent
  with_items:
    - /tmp/imagick-3.4.0RC6
    - imagick-3.4.0RC6.tgz
